services:
  - type: web
    name: bolt-ai-production
    runtime: node
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm run dockerstart
    plan: starter
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5173
      - key: GROQ_API_KEY
        value: ${GROQ_API_KEY}
      - key: HuggingFace_API_KEY
        value: ${HuggingFace_API_KEY}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: ANTHROPIC_API_KEY
        value: ${ANTHROPIC_API_KEY}
      - key: OPEN_ROUTER_API_KEY
        value: ${OPEN_ROUTER_API_KEY}
      - key: GOOGLE_GENERATIVE_AI_API_KEY
        value: ${GOOGLE_GENERATIVE_AI_API_KEY}
      - key: OLLAMA_API_BASE_URL
        value: ${OLLAMA_API_BASE_URL}
      - key: XAI_API_KEY
        value: ${XAI_API_KEY}
      - key: TOGETHER_API_KEY
        value: ${TOGETHER_API_KEY}
      - key: TOGETHER_API_BASE_URL
        value: ${TOGETHER_API_BASE_URL}
      - key: AWS_BEDROCK_CONFIG
        value: ${AWS_BEDROCK_CONFIG}
      - key: VITE_LOG_LEVEL
        value: debug
      - key: DEFAULT_NUM_CTX
        value: 32768
      - key: RUNNING_IN_DOCKER
        value: "true"
  - type: web
    name: bolt-ai-development
    runtime: node
    buildCommand: pnpm install
    startCommand: pnpm run dev --host 0.0.0.0
    plan: starter
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: development
      - key: PORT
        value: 5173
      - key: VITE_HMR_PROTOCOL
        value: ws
      - key: VITE_HMR_HOST
        value: localhost
      - key: VITE_HMR_PORT
        value: 5173
      - key: CHOKIDAR_USEPOLLING
        value: "true"
      - key: WATCHPACK_POLLING
        value: "true"
      - key: GROQ_API_KEY
        value: ${GROQ_API_KEY}
      - key: HuggingFace_API_KEY
        value: ${HuggingFace_API_KEY}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: ANTHROPIC_API_KEY
        value: ${ANTHROPIC_API_KEY}
      - key: OPEN_ROUTER_API_KEY
        value: ${OPEN_ROUTER_API_KEY}
      - key: XAI_API_KEY
        value: ${XAI_API_KEY}
      - key: GOOGLE_GENERATIVE_AI_API_KEY
        value: ${GOOGLE_GENERATIVE_AI_API_KEY}
      - key: OLLAMA_API_BASE_URL
        value: ${OLLAMA_API_BASE_URL}
      - key: TOGETHER_API_KEY
        value: ${TOGETHER_API_KEY}
      - key: TOGETHER_API_BASE_URL
        value: ${TOGETHER_API_BASE_URL}
      - key: AWS_BEDROCK_CONFIG
        value: ${AWS_BEDROCK_CONFIG}
      - key: VITE_LOG_LEVEL
        value: debug
      - key: DEFAULT_NUM_CTX
        value: 32768
      - key: RUNNING_IN_DOCKER
        value: "true"
  - type: web
    name: bolt-ai-prebuild
    runtime: node
    startCommand: pnpm run dockerstart
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5173
      - key: OLLAMA_API_BASE_URL
        value: http://127.0.0.1:11434
      - key: DEFAULT_NUM_CTX
        value: 32768
      - key: RUNNING_IN_DOCKER
        value: "true"
